#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# Pre-Project: https://github.com/moddemod/Campus-daily-crack
# modified-Project: https://github.com/LaureatePoet/HFUTer-Clockin-AutoSubmit
# Author: Poet
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

name: HFUT-Auto-Clockin

on:
  push:
    branches: 
      - main
  watch:
    types: started
  schedule:
    - cron: 20,50 9,10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: Run program
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run: |
          python3 HFUTclockin.py ${ACCOUNT} ${PASSWORD} ${ADDRESS}
